###
GET http://localhost:3000/api/products/7

###
PUT http://localhost:3000/api/products/7
content-type: application/json

{
    "incrementOrDecrement": "true"
}

###
PUT http://localhost:3000/api/products/7
content-type: application/json

{
    "incrementOrDecrement": "false"
}